"use client";
import * as Dialog from "@radix-ui/react-dialog";
import { CheckCircle2, Database, FileText, Search, X } from "lucide-react";
import { useDeferredValue, useMemo, useState } from "react";
import { demoResponse } from "@/lib/fixtures";

const records = demoResponse.citations.map((source, index) => ({ ...source, language: "English", type: index === 2 ? "Programme note" : "Policy brief", status: "Indexed", eligibility: index === 2 }));

export function SourceExplorer() {
  const [search, setSearch] = useState("");
  const deferredSearch = useDeferredValue(search);
  const [type, setType] = useState("All types");
  const [selected, setSelected] = useState<(typeof records)[number] | null>(null);
  const filtered = useMemo(() => records.filter((record) => (type === "All types" || record.type === type) && `${record.title} ${record.snippet}`.toLowerCase().includes(deferredSearch.toLowerCase())), [deferredSearch, type]);
  return <>
    <section className="source-toolbar" aria-label="Source filters"><div><Search size={16} /><input aria-label="Search sources" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search the source catalogue" /></div><label><span className="sr-only">Language</span><select aria-label="Language" disabled><option>English</option></select></label><label><span className="sr-only">Type</span><select aria-label="Type" value={type} onChange={(event) => setType(event.target.value)}><option>All types</option><option>Policy brief</option><option>Programme note</option></select></label><label><span className="sr-only">Status</span><select aria-label="Status" disabled><option>Indexed</option></select></label></section>
    <div className="catalog-layout"><section className="catalog-list" aria-labelledby="catalog-title" aria-busy={search !== deferredSearch}><div className="section-heading"><div><p className="mono-label">Established demo corpus</p><h2 id="catalog-title">Source catalogue</h2></div><span className="count-badge" aria-live="polite">{String(filtered.length).padStart(2, "0")} shown</span></div>{filtered.length ? filtered.map((source, index) => <button type="button" className="source-row" key={source.chunk_id} onClick={() => setSelected(source)}><div className="source-icon"><FileText size={18} /></div><div><p className="mono-label">EVIDENCE {String(index + 1).padStart(2, "0")} · {source.language} · {source.type}</p><h3>{source.title}</h3><p>{source.snippet}</p><div className="source-tags"><span><CheckCircle2 size={12} /> {source.status}</span><span>{source.chunk_id}</span><span>Eligibility data: {source.eligibility ? "present" : "not present"}</span></div></div></button>) : <div className="catalog-empty"><Search size={22} /><h3>No matching source</h3><p>Clear the search or select another supported source type. The small corpus is represented honestly.</p><button type="button" onClick={() => { setSearch(""); setType("All types"); }}>Reset filters</button></div>}</section><aside className="lineage-card"><Database size={22} /><p className="mono-label">Evidence lineage</p><h2>Document → chunk → citation</h2><p>Every demo citation exposes both a chunk identifier and its document relationship. The UI never presents model prose as source material.</p><dl><div><dt>Documents</dt><dd>8</dd></div><div><dt>Chunks</dt><dd>239</dd></div><div><dt>Relations</dt><dd>3</dd></div><div><dt>Query logs</dt><dd>0</dd></div></dl></aside></div>
    <Dialog.Root open={Boolean(selected)} onOpenChange={(open) => { if (!open) setSelected(null); }}><Dialog.Portal><Dialog.Overlay className="dialog-overlay" /><Dialog.Content className="source-detail-dialog" aria-describedby="source-detail-description"><Dialog.Title>{selected?.title}</Dialog.Title><Dialog.Description id="source-detail-description">Sanitized source detail and evidence relationship.</Dialog.Description><Dialog.Close className="dialog-close" aria-label="Close source detail"><X size={17} /></Dialog.Close><p>{selected?.snippet}</p><dl><div><dt>Chunk</dt><dd>{selected?.chunk_id}</dd></div><div><dt>Document relation</dt><dd>{selected?.document_id}</dd></div><div><dt>Language</dt><dd>{selected?.language}</dd></div><div><dt>Type</dt><dd>{selected?.type}</dd></div><div><dt>Status</dt><dd>{selected?.status}</dd></div></dl></Dialog.Content></Dialog.Portal></Dialog.Root>
  </>;
}
