"use client";

import * as Dialog from "@radix-ui/react-dialog";
import { useQuery } from "@tanstack/react-query";
import { CheckCircle2, ChevronLeft, ChevronRight, Database, FileText, Search, X } from "lucide-react";
import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useEffect, useRef, useState } from "react";

import { fetchSource, fetchSources, SetuClientError } from "@/lib/adapters";

function useDebouncedValue(value: string, delay: number) { const [debounced, setDebounced] = useState(value); useEffect(() => { const timer = window.setTimeout(() => setDebounced(value), delay); return () => window.clearTimeout(timer); }, [delay, value]); return debounced; }

export function SourceExplorer() {
  const router = useRouter(); const pathname = usePathname(); const searchParams = useSearchParams();
  const [search, setSearch] = useState(() => searchParams.get("search") ?? "");
  const [language, setLanguage] = useState(() => searchParams.get("language") ?? "");
  const [eligibility, setEligibility] = useState(() => searchParams.get("has_eligibility") ?? "");
  const [page, setPage] = useState(() => Math.max(1, Number(searchParams.get("page") ?? 1) || 1));
  const [selectedId, setSelectedId] = useState<string | null>(() => searchParams.get("source"));
  const debouncedSearch = useDebouncedValue(search, 300); const listRef = useRef<HTMLDivElement>(null);
  useEffect(() => { const params = new URLSearchParams(); if (debouncedSearch) params.set("search", debouncedSearch); if (language) params.set("language", language); if (eligibility) params.set("has_eligibility", eligibility); if (page > 1) params.set("page", String(page)); if (selectedId) params.set("source", selectedId); router.replace(`${pathname}${params.size ? `?${params}` : ""}`, { scroll: false }); }, [debouncedSearch, eligibility, language, page, pathname, router, selectedId]);
  const sources = useQuery({ queryKey: ["sources", debouncedSearch, language, eligibility, page], queryFn: ({ signal }) => fetchSources({ page, page_size: 6, search: debouncedSearch || undefined, language: (language || undefined) as "en" | "hi" | "bn" | undefined, has_eligibility: (eligibility || undefined) as "true" | "false" | undefined }, signal) });
  const detail = useQuery({ queryKey: ["source", selectedId], enabled: Boolean(selectedId), queryFn: ({ signal }) => fetchSource(selectedId!, signal) });
  const moveFocus = (event: React.KeyboardEvent, index: number) => { if (!sources.data?.items.length || !["ArrowDown", "ArrowUp", "Home", "End"].includes(event.key)) return; event.preventDefault(); const max = sources.data.items.length - 1; const next = event.key === "Home" ? 0 : event.key === "End" ? max : event.key === "ArrowDown" ? Math.min(max, index + 1) : Math.max(0, index - 1); listRef.current?.querySelectorAll<HTMLButtonElement>(".source-row")[next]?.focus(); };
  const reset = () => { setSearch(""); setLanguage(""); setEligibility(""); setPage(1); };
  const errorMessage = sources.error instanceof SetuClientError ? sources.error.message : "The source catalogue is temporarily unavailable.";

  return <>
    <section className="source-toolbar" aria-label="Source filters"><div><Search size={16} /><input aria-label="Search sources" value={search} maxLength={100} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="Search titles and publishers" /></div><label><span className="sr-only">Language</span><select aria-label="Language" value={language} onChange={(event) => { setLanguage(event.target.value); setPage(1); }}><option value="">All languages</option><option value="en">English</option><option value="hi">Hindi</option><option value="bn">Bengali</option></select></label><label><span className="sr-only">Eligibility relationship</span><select aria-label="Eligibility relationship" value={eligibility} onChange={(event) => { setEligibility(event.target.value); setPage(1); }}><option value="">All evidence</option><option value="true">Eligibility criteria</option><option value="false">Research only</option></select></label></section>
    <div className="catalog-layout"><section className="catalog-list" aria-labelledby="catalog-title" aria-busy={sources.isFetching}><div className="section-heading"><div><p className="mono-label">Server-selected catalogue adapter</p><h2 id="catalog-title">Source catalogue</h2></div><span className="count-badge" aria-live="polite">{sources.data ? `${sources.data.total} matching` : "Loading"}</span></div>
      {sources.isPending ? <div className="catalog-state" role="status"><span className="route-state-mark" />Loading sanitized source metadata…</div> : sources.isError ? <div className="catalog-state catalog-error" role="alert"><h3>Catalogue unavailable</h3><p>{errorMessage}</p><button type="button" onClick={() => sources.refetch()}>Try again</button></div> : sources.data.items.length ? <div ref={listRef}>{sources.data.items.map((source, index) => <button type="button" className="source-row" key={source.id} onClick={() => setSelectedId(source.id)} onKeyDown={(event) => moveFocus(event, index)}><div className="source-icon"><FileText size={18} /></div><div><p className="mono-label">{source.source} · {source.language.toUpperCase()} · {source.chunk_count} chunks</p><h3>{source.title ?? "Untitled source"}</h3><p>Sanitized catalogue metadata. Full source bodies and unrestricted chunks are never returned.</p><div className="source-tags"><span><CheckCircle2 size={12} /> Indexed</span><span>{source.id}</span><span>Eligibility: {source.eligibility_count}</span></div></div></button>)}</div> : <div className="catalog-empty"><Search size={22} /><h3>No matching source</h3><p>Clear the search or adjust the supported filters. Empty results are shown without inventing catalogue records.</p><button type="button" onClick={reset}>Reset filters</button></div>}
      {sources.data && sources.data.total_pages > 1 && <nav className="catalog-pagination" aria-label="Source pages"><button type="button" disabled={page <= 1} onClick={() => setPage((value) => Math.max(1, value - 1))}><ChevronLeft size={15} /> Previous</button><span>Page {page} of {sources.data.total_pages}</span><button type="button" disabled={page >= sources.data.total_pages} onClick={() => setPage((value) => value + 1)}>Next <ChevronRight size={15} /></button></nav>}
    </section><aside className="lineage-card"><Database size={22} /><p className="mono-label">Established local corpus</p><h2>Document → chunk → citation</h2><p>The explorer returns bounded metadata and relationship counts through the BFF. The frozen baseline contains eight documents; results may be a filtered or demo subset.</p><dl><div><dt>Documents</dt><dd>8</dd></div><div><dt>Chunks</dt><dd>239</dd></div><div><dt>Eligibility records</dt><dd>3</dd></div><div><dt>Query logs</dt><dd>0</dd></div></dl></aside></div>
    <Dialog.Root open={Boolean(selectedId)} onOpenChange={(open) => { if (!open) setSelectedId(null); }}><Dialog.Portal><Dialog.Overlay className="dialog-overlay" /><Dialog.Content className="source-detail-dialog" aria-describedby="source-detail-description"><Dialog.Title>{detail.data?.title ?? (detail.isPending ? "Loading source…" : "Source detail")}</Dialog.Title><Dialog.Description id="source-detail-description">Sanitized source metadata, counts and criteria relationships.</Dialog.Description><Dialog.Close className="dialog-close" aria-label="Close source detail"><X size={17} /></Dialog.Close>{detail.isPending ? <div className="catalog-state" role="status">Loading bounded detail…</div> : detail.isError ? <div className="catalog-state catalog-error" role="alert"><p>{detail.error instanceof SetuClientError ? detail.error.message : "Source detail is unavailable."}</p></div> : detail.data && <><dl><div><dt>Publisher</dt><dd>{detail.data.source}</dd></div><div><dt>Language</dt><dd>{detail.data.language.toUpperCase()}</dd></div><div><dt>Chunks</dt><dd>{detail.data.chunk_count}</dd></div><div><dt>Eligibility relations</dt><dd>{detail.data.eligibility_count}</dd></div>{Object.entries(detail.data.metadata).map(([key, value]) => <div key={key}><dt>{key.replace(/_/g, " ")}</dt><dd>{value}</dd></div>)}</dl>{detail.data.eligibility.length > 0 && <section className="detail-criteria"><h3>Eligibility criteria summary</h3>{detail.data.eligibility.map((record) => <article key={record.scheme_name}><strong>{record.scheme_name}</strong><dl>{Object.entries(record.criteria).map(([key, value]) => <div key={key}><dt>{key.replace(/_/g, " ")}</dt><dd>{Array.isArray(value) ? value.join(", ") : String(value)}</dd></div>)}</dl></article>)}</section>}<div className="detail-links"><Link href={`/workspace?q=${encodeURIComponent(`What evidence supports ${detail.data.title ?? "this source"}?`)}`}>Ask a supported question</Link>{detail.data.has_eligibility && <Link href="/workspace">Open eligibility workflow</Link>}</div></>}</Dialog.Content></Dialog.Portal></Dialog.Root>
  </>;
}
