"""Answers for traffic-fine questions, composed from premise checks (Phase 3).

Every sentence here is a fixed template filled with values from the verified
offence tables, so nothing is generated by a model and no amount can appear
that is not in a VERIFIED state notification. Templates exist in English,
Hindi and Bengali. The tone is calm: SETU never tells a person to refuse,
argue or that an officer is wrong; it states what the notification says and
how to pay or contest through official channels.
"""

from __future__ import annotations

from datetime import date
from typing import Any

from app.agent.premise import SUPPORTED_JURISDICTIONS, QueryFacts, check_premise, load_table

STATE_NAMES = {
    "en": {"IN-WB": "West Bengal", "IN-KA": "Karnataka", "IN-DL": "Delhi"},
    "hi": {"IN-WB": "पश्चिम बंगाल", "IN-KA": "कर्नाटक", "IN-DL": "दिल्ली"},
    "bn": {"IN-WB": "পশ্চিমবঙ্গ", "IN-KA": "কর্ণাটক", "IN-DL": "দিল্লি"},
}
OFFENCE_NAMES = {
    "en": {
        "helmet": "riding without a helmet",
        "phone_device": "using a handheld phone while driving",
        "no_licence": "driving without a licence",
        "no_insurance": "driving without insurance",
        "overspeeding": "overspeeding",
        "triple_riding": "carrying more than one pillion rider",
    },
    "hi": {
        "helmet": "बिना हेलमेट वाहन चलाने",
        "phone_device": "गाड़ी चलाते समय हाथ में फ़ोन इस्तेमाल करने",
        "no_licence": "बिना लाइसेंस गाड़ी चलाने",
        "no_insurance": "बिना बीमा गाड़ी चलाने",
        "overspeeding": "तेज़ रफ़्तार (ओवरस्पीडिंग)",
        "triple_riding": "दोपहिया पर एक से अधिक पीछे बैठी सवारी",
    },
    "bn": {
        "helmet": "হেলমেট ছাড়া চালানো",
        "phone_device": "গাড়ি চালানোর সময় হাতে ফোন ব্যবহার",
        "no_licence": "লাইসেন্স ছাড়া গাড়ি চালানো",
        "no_insurance": "বিমা ছাড়া গাড়ি চালানো",
        "overspeeding": "অতিরিক্ত গতি",
        "triple_riding": "দুই চাকায় একজনের বেশি পিছনের আরোহী",
    },
}
OCCURRENCE_NAMES = {
    "en": {"first": "first offence", "subsequent": "repeat offence", "any": ""},
    "hi": {"first": "पहली बार", "subsequent": "दोबारा", "any": ""},
    "bn": {"first": "প্রথমবার", "subsequent": "পুনরায়", "any": ""},
}
VEHICLE_NAMES = {
    "en": {
        "any": "", "two_three_wheeler": "two- and three-wheelers", "light_motor_vehicle": "light motor vehicles",
        "two_three_wheeler_and_lmv": "two- and three-wheelers and light motor vehicles",
        "medium_heavy": "medium and heavy vehicles", "heavy_and_others": "heavy and other vehicles", "others": "other vehicles",
    },
    "hi": {
        "any": "", "two_three_wheeler": "दोपहिया/तिपहिया", "light_motor_vehicle": "हल्के मोटर वाहन",
        "two_three_wheeler_and_lmv": "दोपहिया/तिपहिया और हल्के वाहन",
        "medium_heavy": "मध्यम/भारी वाहन", "heavy_and_others": "भारी व अन्य वाहन", "others": "अन्य वाहन",
    },
    "bn": {
        "any": "", "two_three_wheeler": "দুই/তিন চাকা", "light_motor_vehicle": "হালকা মোটরযান",
        "two_three_wheeler_and_lmv": "দুই/তিন চাকা ও হালকা যান",
        "medium_heavy": "মাঝারি/ভারী যান", "heavy_and_others": "ভারী ও অন্যান্য যান", "others": "অন্যান্য যান",
    },
}
TEXT = {
    "en": {
        "lookup": "The official on-the-spot amount in {state} for {offence} is {amounts}, under {reference} ({row}).",
        "supported": "{claim} matches this amount.",
        "contradicted": "{claim} does not match this amount.",
        "unverified": "SETU has no verified on-the-spot amount for {offence} in {state} yet, so it cannot confirm or rule out {claim}.",
        "some_amount": "an amount",
        "legal_review": "SETU does not show an amount for red-light jumping. It depends on whether it is booked as a signal violation or as dangerous driving, and this is under legal review.",
        "not_named": "Earphones for music are not named in Section 184 of the Motor Vehicles Act, so SETU cannot confirm or rule out an amount. Some police fine lists book them under Section 184.",
        "not_covered": "SETU has verified fine tables only for West Bengal, Karnataka and Delhi so far.",
        "not_in_force": "The {state} notification SETU has for {offence} was not yet in force on the date you asked about, and SETU has no verified amount for that date.",
        "ask_place": "Which state or city are you in? On-the-spot amounts differ by state. SETU covers West Bengal, Karnataka and Delhi.",
        "ask_offence": "Which offence is this about? Please ask about one offence at a time.",
        "guidance": "Pay only through an e-challan or an official receipt. If you disagree, you can contest the challan later through official channels. Not legal advice.",
    },
    "hi": {
        "lookup": "{state} में {offence} के लिए मौके पर आधिकारिक जुर्माना {amounts} है ({reference}, {row})।",
        "supported": "{claim} इस राशि से मेल खाता है।",
        "contradicted": "{claim} इस राशि से मेल नहीं खाता।",
        "unverified": "{state} में {offence} के लिए SETU के पास अभी कोई सत्यापित राशि नहीं है, इसलिए वह {claim} की पुष्टि या खंडन नहीं कर सकता।",
        "some_amount": "किसी राशि",
        "legal_review": "लाल बत्ती पार करने के लिए SETU कोई राशि नहीं दिखाता। यह इस पर निर्भर है कि इसे सिग्नल उल्लंघन के रूप में दर्ज किया गया या खतरनाक ड्राइविंग के रूप में, और इस पर कानूनी समीक्षा चल रही है।",
        "not_named": "संगीत सुनने वाले ईयरफ़ोन का मोटर वाहन अधिनियम की धारा 184 में नाम नहीं है, इसलिए SETU किसी राशि की पुष्टि या खंडन नहीं कर सकता। कुछ पुलिस जुर्माना सूचियाँ इन्हें धारा 184 में दर्ज करती हैं।",
        "not_covered": "SETU के पास अभी केवल पश्चिम बंगाल, कर्नाटक और दिल्ली की सत्यापित जुर्माना तालिकाएँ हैं।",
        "not_in_force": "{offence} के लिए SETU के पास {state} की जो अधिसूचना है, वह आपकी पूछी गई तारीख पर लागू नहीं थी, और उस तारीख की कोई सत्यापित राशि SETU के पास नहीं है।",
        "ask_place": "आप किस राज्य या शहर में हैं? मौके पर जुर्माने की राशि हर राज्य में अलग होती है। SETU पश्चिम बंगाल, कर्नाटक और दिल्ली को कवर करता है।",
        "ask_offence": "यह किस अपराध के बारे में है? कृपया एक बार में एक अपराध के बारे में पूछें।",
        "guidance": "भुगतान केवल ई-चालान या आधिकारिक रसीद के ज़रिए करें। असहमत हों तो बाद में आधिकारिक माध्यमों से चालान को चुनौती दे सकते हैं। यह कानूनी सलाह नहीं है।",
    },
    "bn": {
        "lookup": "{state}-এ {offence}-এর জন্য ঘটনাস্থলে সরকারি জরিমানার পরিমাণ {amounts} ({reference}, {row})।",
        "supported": "{claim} এই পরিমাণের সঙ্গে মেলে।",
        "contradicted": "{claim} এই পরিমাণের সঙ্গে মেলে না।",
        "unverified": "{state}-এ {offence}-এর জন্য SETU-র কাছে এখনও কোনো যাচাই করা পরিমাণ নেই, তাই {claim} নিশ্চিত বা বাতিল করা যাচ্ছে না।",
        "some_amount": "কোনো পরিমাণ",
        "legal_review": "লাল বাতি অমান্য করার জন্য SETU কোনো পরিমাণ দেখায় না। এটি সিগন্যাল লঙ্ঘন না বিপজ্জনক ড্রাইভিং হিসেবে নথিভুক্ত হয়েছে তার উপর নির্ভর করে, এবং বিষয়টি আইনি পর্যালোচনাধীন।",
        "not_named": "গান শোনার ইয়ারফোনের কথা মোটর ভেহিকেলস আইনের ১৮৪ ধারায় উল্লেখ নেই, তাই SETU কোনো পরিমাণ নিশ্চিত বা বাতিল করতে পারে না। কিছু পুলিশের জরিমানার তালিকায় এটি ১৮৪ ধারায় ধরা হয়।",
        "not_covered": "SETU-র কাছে এখন শুধু পশ্চিমবঙ্গ, কর্ণাটক ও দিল্লির যাচাই করা জরিমানার তালিকা আছে।",
        "not_in_force": "{offence}-এর জন্য SETU-র কাছে {state}-এর যে বিজ্ঞপ্তি আছে, তা আপনার জিজ্ঞাসিত তারিখে কার্যকর ছিল না, এবং সেই তারিখের কোনো যাচাই করা পরিমাণ SETU-র কাছে নেই।",
        "ask_place": "আপনি কোন রাজ্য বা শহরে আছেন? ঘটনাস্থলের জরিমানা রাজ্যভেদে আলাদা। SETU পশ্চিমবঙ্গ, কর্ণাটক ও দিল্লি কভার করে।",
        "ask_offence": "এটি কোন অপরাধ নিয়ে? অনুগ্রহ করে একবারে একটি অপরাধ নিয়ে জিজ্ঞাসা করুন।",
        "guidance": "কেবল ই-চালান বা সরকারি রসিদের মাধ্যমে টাকা দিন। একমত না হলে পরে সরকারি পথে চালানের বিরুদ্ধে আপত্তি জানাতে পারেন। এটি আইনি পরামর্শ নয়।",
    },
}


def format_inr(value: int) -> str:
    """Indian digit grouping: 100000 -> ₹1,00,000."""
    digits = str(value)
    if len(digits) <= 3:
        return f"₹{digits}"
    head, tail = digits[:-3], digits[-3:]
    groups = []
    while len(head) > 2:
        groups.insert(0, head[-2:])
        head = head[:-2]
    if head:
        groups.insert(0, head)
    return "₹" + ",".join(groups + [tail])


def _amounts_text(amounts: list[dict[str, Any]], language: str) -> str:
    parts = []
    for amount in amounts:
        qualifiers = [
            label
            for label in (
                OCCURRENCE_NAMES[language].get(amount["occurrence"], ""),
                VEHICLE_NAMES[language].get(amount["vehicle_class"], amount["vehicle_class"]),
            )
            if label
        ]
        parts.append(format_inr(amount["inr"]) + (f" ({', '.join(qualifiers)})" if qualifiers else ""))
    return "; ".join(parts)


def compose(
    query: str,
    facts: QueryFacts,
    language: str,
    requested_jurisdiction: str | None = None,
    as_of: date | None = None,
) -> dict[str, Any]:
    """Return an agent state update: answer, sections, status and a structured premise_check."""
    text = TEXT[language]
    jurisdiction = facts.jurisdiction or (requested_jurisdiction if requested_jurisdiction in SUPPORTED_JURISDICTIONS else None)

    def update(status: str, sentences: list[str], check: dict[str, Any] | None) -> dict[str, Any]:
        answer = " ".join(sentences)
        return {
            "answer": answer,
            "sections": [{"text": sentence, "citation_ids": []} for sentence in sentences],
            "citations": [],
            "confidence": None,
            "route": "traffic_rules",
            "response_status": status,
            "premise_check": check,
        }

    if len(facts.offences) > 1:
        return update("needs_clarification", [text["ask_offence"]], {"verdict": "ambiguous_offence", "missing": ["offence"]})
    if not facts.place_supported and jurisdiction is None:
        return update("rule_lookup", [text["not_covered"]], {"verdict": "not_covered", "offence_id": facts.offence_id})
    if jurisdiction is None:
        return update("needs_clarification", [text["ask_place"]], {"verdict": "missing_jurisdiction", "missing": ["jurisdiction"], "offence_id": facts.offence_id})

    check = check_premise(query, load_table(jurisdiction), facts, as_of)
    check["jurisdiction"] = jurisdiction
    verdict = check["verdict"]
    claim = format_inr(check["claimed_inr"]) if check["claimed_inr"] is not None else text["some_amount"]
    state = STATE_NAMES[language][jurisdiction]
    offence = OFFENCE_NAMES[language].get(check["offence_id"] or "", "")

    if verdict == "legal_review":
        sentences = [text["legal_review"]]
    elif verdict == "not_named":
        sentences = [text["not_named"]]
    elif verdict == "not_in_force":
        sentences = [text["not_in_force"].format(state=state, offence=offence)]
    elif verdict == "unverified":
        sentences = [text["unverified"].format(state=state, offence=offence, claim=claim)]
    else:
        sentences = [
            text["lookup"].format(
                state=state,
                offence=offence,
                amounts=_amounts_text(check["verified_amounts"], language),
                reference=check["source"]["reference"],
                row=check["schedule_row"],
            )
        ]
        if verdict in ("supported", "contradicted"):
            sentences.append(text[verdict].format(claim=claim))
    sentences.append(text["guidance"])
    return update("rule_lookup", sentences, check)
