"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { ArrowLeft, ArrowRight, CheckCircle2, CircleAlert, RotateCcw, ShieldCheck } from "lucide-react";

import { bffAdapter, SetuClientError } from "@/lib/adapters";
import type { Citation } from "@/lib/contracts";

type SchemeId = "scholarship" | "kisan" | "jandhan";
type Outcome = "eligible" | "not-eligible" | "insufficient";
type Profile = { income: string; category: string; landholding: string; excluded: string; age: string; documents: string };

const schemes = {
  scholarship: { name: "Post-Matric Scholarship", sourceId: "eligibility-source-01", description: "Family-income and category criteria", fields: ["income", "category"] as const },
  kisan: { name: "PM Kisan Samman Nidhi", sourceId: "eligibility-source-02", description: "Landholding and exclusion criteria", fields: ["landholding", "excluded"] as const },
  jandhan: { name: "Pradhan Mantri Jan Dhan Yojana", sourceId: "eligibility-source-03", description: "Age and document-readiness criteria", fields: ["age", "documents"] as const },
};
const emptyProfile: Profile = { income: "", category: "", landholding: "", excluded: "", age: "", documents: "" };

function evaluate(schemeId: SchemeId, profile: Profile): { outcome: Outcome; criteria: { label: string; state: "pass" | "fail" | "missing"; explanation: string }[]; missing: string[] } {
  const missing: string[] = [];
  if (schemeId === "scholarship") {
    const income = profile.income ? Number(profile.income) : null; if (income === null) missing.push("annual family income"); if (!profile.category) missing.push("applicant category");
    const criteria = [{ label: "Family income", state: income === null ? "missing" as const : income <= 250000 ? "pass" as const : "fail" as const, explanation: income === null ? "Income was not supplied." : `Compared with the stored ₹250,000 threshold.` }, { label: "Supported category", state: !profile.category ? "missing" as const : ["SC", "ST", "OBC", "Minority", "Current-guideline category"].includes(profile.category) ? "pass" as const : "fail" as const, explanation: profile.category ? `The selected category is ${profile.category}.` : "Category was not supplied." }];
    return { outcome: missing.length ? "insufficient" : criteria.some((item) => item.state === "fail") ? "not-eligible" : "eligible", criteria, missing };
  }
  if (schemeId === "kisan") {
    if (!profile.landholding) missing.push("landholding-family status"); if (!profile.excluded) missing.push("exclusion-category response");
    const criteria = [{ label: "Landholding family", state: !profile.landholding ? "missing" as const : profile.landholding === "yes" ? "pass" as const : "fail" as const, explanation: profile.landholding ? "The stored criteria specify no upper landholding limit and require current-guideline verification." : "Landholding-family status was not supplied." }, { label: "Exclusion check", state: !profile.excluded ? "missing" as const : profile.excluded === "no" ? "pass" as const : "fail" as const, explanation: profile.excluded ? `Exclusion response: ${profile.excluded}.` : "Exclusion response was not supplied." }];
    return { outcome: missing.length ? "insufficient" : criteria.some((item) => item.state === "fail") ? "not-eligible" : "eligible", criteria, missing };
  }
  const age = profile.age ? Number(profile.age) : null; if (age === null) missing.push("age band"); if (!profile.documents) missing.push("document-readiness response");
  const criteria = [{ label: "Minimum age", state: age === null ? "missing" as const : age >= 10 ? "pass" as const : "fail" as const, explanation: age === null ? "Age was not supplied." : "Compared with the stored minimum-age criterion." }, { label: "Document readiness", state: !profile.documents ? "missing" as const : profile.documents === "yes" ? "pass" as const : "missing" as const, explanation: profile.documents === "yes" ? "Required document types are available." : "Document identifiers are never requested; only readiness is checked." }];
  return { outcome: missing.length || profile.documents === "no" ? "insufficient" : criteria.some((item) => item.state === "fail") ? "not-eligible" : "eligible", criteria, missing: profile.documents === "no" ? [...missing, "required document types"] : missing };
}

export function EligibilityWorkflow() {
  const [step, setStep] = useState<"scheme" | "profile" | "review" | "result">("scheme"); const [schemeId, setSchemeId] = useState<SchemeId>("scholarship"); const [profile, setProfile] = useState<Profile>(emptyProfile); const [citations, setCitations] = useState<Citation[]>([]); const [error, setError] = useState<string | null>(null);
  const scheme = schemes[schemeId]; const evaluation = useMemo(() => evaluate(schemeId, profile), [schemeId, profile]);
  const mutation = useMutation({ retry: false, mutationFn: () => bffAdapter.query({ query: `Eligibility assessment: Evaluate ${scheme.name} using only this session profile: ${scheme.fields.map((field) => `${field}=${profile[field] || "not supplied"}`).join(", ")}. Provide informational evidence, not an official decision.`, language: "en" }), onSuccess: (result) => { setCitations(result.citations); setStep("result"); }, onError: (reason) => setError(reason instanceof SetuClientError ? reason.message : "The informational assessment could not be prepared.") });
  const update = (key: keyof Profile, value: string) => setProfile((current) => ({ ...current, [key]: value }));
  const reset = () => { setProfile(emptyProfile); setCitations([]); setError(null); mutation.reset(); setStep("scheme"); };
  return <section className="eligibility-flow" aria-labelledby="eligibility-heading">
    <div className="eligibility-notice"><ShieldCheck size={18} /><p><strong>Private, session-only assessment</strong><span>SETU provides evidence-backed informational guidance, not an official eligibility decision.</span></p></div>
    <ol className="eligibility-steps" aria-label="Eligibility workflow progress">{["Scheme", "Profile", "Review", "Result"].map((label, index) => <li key={label} aria-current={["scheme", "profile", "review", "result"].indexOf(step) === index ? "step" : undefined}><span>{index + 1}</span>{label}</li>)}</ol>
    {step === "scheme" && <div className="eligibility-card"><p className="mono-label">Step 01 · programme</p><h3 id="eligibility-heading">Choose a supported criteria set</h3><div className="scheme-grid">{(Object.entries(schemes) as [SchemeId, typeof scheme][]).map(([id, item]) => <button type="button" key={id} className={schemeId === id ? "is-selected" : ""} aria-pressed={schemeId === id} onClick={() => setSchemeId(id)}><strong>{item.name}</strong><span>{item.description}</span></button>)}</div><div className="flow-actions"><button type="button" className="button button-primary" onClick={() => setStep("profile")}>Continue <ArrowRight size={15} /></button></div></div>}
    {step === "profile" && <div className="eligibility-card"><p className="mono-label">Step 02 · minimal profile</p><h3>{scheme.name}</h3><p className="form-intro">Only rule-relevant, non-identifying answers are requested. Leave an answer blank to see an insufficient-information result.</p><div className="profile-grid">
      {schemeId === "scholarship" && <><label>Annual family income (₹)<span>Used only for the current browser session.</span><input inputMode="numeric" min="0" type="number" value={profile.income} onChange={(event) => update("income", event.target.value)} /></label><label>Applicant category<span>Choose the criteria category; no certificate number is collected.</span><select value={profile.category} onChange={(event) => update("category", event.target.value)}><option value="">Not supplied</option><option>SC</option><option>ST</option><option>OBC</option><option>Minority</option><option>Current-guideline category</option><option>General</option></select></label></>}
      {schemeId === "kisan" && <><label>Landholding farmer family?<span>The stored rule has no upper landholding limit and requires current-guideline verification.</span><select value={profile.landholding} onChange={(event) => update("landholding", event.target.value)}><option value="">Not supplied</option><option value="yes">Yes</option><option value="no">No</option></select></label><label>Listed exclusion category?<span>Income-tax payers and institutional landholders are listed exclusions.</span><select value={profile.excluded} onChange={(event) => update("excluded", event.target.value)}><option value="">Not supplied</option><option value="no">No</option><option value="yes">Yes</option></select></label></>}
      {schemeId === "jandhan" && <><label>Applicant age<span>No birth date is collected.</span><input inputMode="numeric" min="0" max="120" type="number" value={profile.age} onChange={(event) => update("age", event.target.value)} /></label><label>Required document types available?<span>No document numbers or uploads are collected.</span><select value={profile.documents} onChange={(event) => update("documents", event.target.value)}><option value="">Not supplied</option><option value="yes">Yes</option><option value="no">No / unsure</option></select></label></>}
    </div><div className="flow-actions"><button type="button" className="button button-secondary" onClick={() => setStep("scheme")}><ArrowLeft size={15} /> Back</button><button type="button" className="button button-primary" onClick={() => setStep("review")}>Review <ArrowRight size={15} /></button></div></div>}
    {step === "review" && <div className="eligibility-card"><p className="mono-label">Step 03 · review</p><h3>Review the criteria inputs</h3><dl className="review-list"><div><dt>Programme</dt><dd>{scheme.name}</dd></div>{scheme.fields.map((field) => <div key={field}><dt>{field.replace(/_/g, " ")}</dt><dd>{profile[field] || "Not supplied"}</dd></div>)}</dl><p className="privacy-copy">Answers are held only in component memory for this browser session and are not written to local storage or the database.</p>{error && <div className="inline-error" role="alert">{error}</div>}<div className="flow-actions"><button type="button" className="button button-secondary" onClick={() => setStep("profile")}><ArrowLeft size={15} /> Edit</button><button type="button" className="button button-primary" disabled={mutation.isPending} onClick={() => { if (!mutation.isPending) { setError(null); mutation.mutate(); } }}>{mutation.isPending ? "Preparing guidance…" : "Prepare guidance"}</button></div></div>}
    {step === "result" && <div className={`eligibility-card eligibility-result result-${evaluation.outcome}`}><p className="mono-label">Step 04 · informational result</p><div className="result-title">{evaluation.outcome === "eligible" ? <CheckCircle2 /> : <CircleAlert />}<div><h3>{evaluation.outcome === "eligible" ? "Appears to meet the supplied criteria" : evaluation.outcome === "not-eligible" ? "A supplied criterion does not match" : "More information is needed"}</h3><p>{evaluation.outcome === "insufficient" ? `Missing: ${evaluation.missing.join(", ") || "required supporting information"}.` : "This is an evidence-backed explanation, not an official decision."}</p></div></div><div className="criteria-results">{evaluation.criteria.map((criterion) => <article key={criterion.label}><span className={`criterion-state state-${criterion.state}`}>{criterion.state}</span><h4>{criterion.label}</h4><p>{criterion.explanation}</p></article>)}</div><div className="result-evidence"><strong>Supporting evidence</strong>{citations.length ? citations.map((citation) => <Link key={citation.chunk_id} href={`/sources?source=${encodeURIComponent(citation.document_id)}`}>{citation.title ?? "View source"}</Link>) : <span>No supporting citation was returned.</span>}<Link href={`/sources?source=${scheme.sourceId}`}>Review the stored criteria summary</Link></div><div className="flow-actions"><button type="button" className="button button-secondary" onClick={() => setStep("profile")}><ArrowLeft size={15} /> Edit answers</button><button type="button" className="button button-primary" onClick={reset}><RotateCcw size={15} /> Start over</button></div></div>}
  </section>;
}
