import { describe, expect, it, vi } from "vitest";

import { demoResponse, establishedQuestion } from "@/lib/fixtures";
import { BffError, localBackendOrigin, queryThroughBff, sourcesThroughBff, validateSameSite } from "@/lib/server/bff";

const localEnvironment = { NODE_ENV: "test", SETU_DATA_MODE: "local", SETU_BACKEND_URL: "http://127.0.0.1:8000", SETU_BACKEND_API_KEY: "server-only-test-key" } as NodeJS.ProcessEnv;

describe("server-only BFF boundary", () => {
  it("keeps demo mode network-free", async () => { const transport = vi.fn(); const response = await queryThroughBff(establishedQuestion, { transport, environment: { NODE_ENV: "test", SETU_DATA_MODE: "demo" } }); expect(response).toEqual(demoResponse); expect(transport).not.toHaveBeenCalled(); });
  it("keeps the future cloud adapter fail-closed", async () => { await expect(queryThroughBff(establishedQuestion, { environment: { NODE_ENV: "test", SETU_DATA_MODE: "cloud" } })).rejects.toMatchObject({ code: "CLOUD_ADAPTER_DISABLED" }); });
  it("allows only configured loopback HTTP origins", () => { expect(localBackendOrigin(localEnvironment)).toBe("http://127.0.0.1:8000"); for (const value of ["https://127.0.0.1:8000", "http://backend.example", "http://127.0.0.1:8000/path", "http://user:pass@localhost:8000"]) expect(() => localBackendOrigin({ NODE_ENV: "test", SETU_BACKEND_URL: value })).toThrow(BffError); });
  it("attaches the API key only to one server-side attempt", async () => { const transport = vi.fn(async (_url: string | URL | Request, init?: RequestInit) => { expect(new Headers(init?.headers).get("X-API-Key")).toBe("server-only-test-key"); return new Response(JSON.stringify(demoResponse), { status: 200, headers: { "Content-Type": "application/json" } }); }); const result = await queryThroughBff(establishedQuestion, { transport: transport as typeof fetch, environment: localEnvironment }); expect(result.answer).toBe(demoResponse.answer); expect(JSON.stringify(result)).not.toContain("server-only-test-key"); expect(transport).toHaveBeenCalledTimes(1); });
  it("does not retry upstream failures and sanitizes them", async () => { const transport = vi.fn(async () => new Response("upstream secret body", { status: 500 })); await expect(queryThroughBff(establishedQuestion, { transport: transport as typeof fetch, environment: localEnvironment })).rejects.toMatchObject({ code: "BACKEND_UNAVAILABLE", message: "The backend is temporarily unavailable." }); expect(transport).toHaveBeenCalledTimes(1); });
  it("rejects malformed backend data", async () => { const transport = vi.fn(async () => new Response(JSON.stringify({ answer: 42, api_key: "leak" }), { status: 200 })); await expect(queryThroughBff(establishedQuestion, { transport: transport as typeof fetch, environment: localEnvironment })).rejects.toMatchObject({ code: "MALFORMED_RESPONSE" }); });
  it("rejects cross-site origins", () => { expect(validateSameSite(new Request("http://127.0.0.1:3000/api/query", { headers: { Origin: "https://evil.example", "Sec-Fetch-Site": "cross-site" } }))).toBe(false); expect(validateSameSite(new Request("http://127.0.0.1:3000/api/query", { headers: { Origin: "http://127.0.0.1:3000", "Sec-Fetch-Site": "same-origin" } }))).toBe(true); });
  it("bounds source pagination before any transport", async () => { const transport = vi.fn(); await expect(sourcesThroughBff(new URL("http://localhost/api/sources?page_size=26"), { transport, environment: localEnvironment })).rejects.toMatchObject({ code: "INVALID_REQUEST" }); expect(transport).not.toHaveBeenCalled(); });
});
